# Generated by Django 4.2.4 on 2023-08-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Заговолок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('authors', models.CharField(max_length=64, verbose_name='Автор')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(verbose_name='Цена')),
                ('auction', models.BooleanField(default=False, verbose_name='Торг')),
            ],
        ),
    ]
