# Generated by Django 4.2.4 on 2023-08-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0002_alter_advertisement_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='media', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
