# Generated by Django 4.2.4 on 2023-08-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisment', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table=None,
        ),
    ]
